### register user
POST http://localhost:3000/auth/register
Content-Type: application/json  

{
  "email": "john@example.com",
  "password": "Test@123",
  "name": "John Doe"
}

### login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "Test@123"
}